### ISSUE TITLE
CkEditor.razor SetData() async

### ISSUE THREAD

**Issue by brucelinker** [ParadiseFallen/Blazor.CkEditor5#2]
In my VS2022, I am seeing a message on the SetData() method on line31:
![image](https://user-images.githubusercontent.com/25513852/159169229-d21f6b5b-b900-4955-a16c-bc1994aed1fd.png)

The way I have fixed this was to change:
```
public async Task SetData(string content)
{
    await JsEditorInstance.InvokeVoidAsync("data.set", content);
}
```

to 
```
public void SetData(string content)
{
    JsEditorInstance.InvokeVoidAsync("data.set", content);
}
```

Everything still works great and no warning message.

I hope this works for you. -- Bruce

**Comment by ParadiseFallen** [comment]
Well. that's not a fix really. you just move that error to a method that now ignores awaiting. SetData should be async because it call js interop. This lib leaves the decision to the developer about async. You should't call it in setter also. If you wanna put in in setter you can 
```cs
SetData().GetAwaiter().GetResult()
```
